server:
  url: http://localhost
  port: 8080

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    url: jdbc:mysql://localhost:3306/escola
    username: root
    password: facadojoao@ie
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  flyway:
    enabled: true
    locations: src/main/resources/db/migration
    schemas: escola
    baseline-on-migrate: true
    baseline-version: 1
    sql-migration-prefix: V
    sql-migration-suffixes: .sql
    url: jdbc:mysql://localhost:3306/escola?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
    user: root
    password: facadojoao@ie

